graph LR
    A(Dataset)
    B(Data Understanding Agent)
    C(Data Assessing Agent)
    
    subgraph data_preprocessing_loop[Data Preprocessing Loop]
        D(Data Cleaning Agent)
        E(In-Loop Assessing Agent)
    end

    F(Business Questions Agent)

    subgraph eda_agent_sequence[EDA Agent Sequence]
        G(Data Preparation Agent)
        H(Insight Gatherer Agent)
        I(Data Explainer Agent)
    end

    J(Final Report)

    A --> B
    B --> C
    C --> data_preprocessing_loop
    D --> E
    E --> D
    data_preprocessing_loop --> F
    F --> eda_agent_sequence
    G --> H
    H --> I
    eda_agent_sequence --> J

    style A fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style B fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style C fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style D fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style E fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style F fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style G fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style H fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style I fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style J fill:#f6f7f7,stroke:#416396,stroke-width:4px
    style data_preprocessing_loop fill:#a0cefd20,stroke:#416396,stroke-width:4px
    style eda_agent_sequence fill:#a0cefd20,stroke:#416396,stroke-width:4px